### ISSUE TITLE
Rebuild the screen "lib\screens\player\rules_pdf_viewer.dart" in the "2023" branch.

### ISSUE THREAD

**Issue by Mehul-Kumar-27** [iiitv/Arcadia-Auction#22]
## Suggested Solution 
The PDF Viewer package currently employed within the application has been deprecated. To address this issue and ensure optimal functionality, it is strongly recommended to adopt the latest version of the "syncfusion_flutter_pdf" package and seamlessly integrate it with the existing codebase.

**Comment by aspiringgarv** [comment]
Could you assign this issue to me will be happy to contribute.
