### ISSUE TITLE
Add Flutter CI Workflow

### ISSUE THREAD

**Issue by andoriyaprashant** [iiitv/Arcadia-Auction#28]
Requesting the addition of a Flutter CI workflow to our Arcadia-Auction repo. This automation will help us automatically test and deploy our Flutter application, ensuring stability and reliability throughout the development process. It's a valuable enhancement that can streamline our workflow and improve the overall quality of our app. If you believe this enhancement is valuable, please assign it to me for implementation. Thank you!

**Comment by Mehul-Kumar-27** [comment]
Great thought, @andoriyaprashant ! Please take this issue forward. 👍
