### ISSUE TITLE
Pixel Overflow Error in "Upcoming Match Card"

### ISSUE THREAD

**Issue by Mehul-Kumar-27** [iiitv/Arcadia-Auction#29]
### Issue Description
This issue aims to resolve a pixel overflow error occurring in the "lib/widgets/upcoming_match_card.dart" file. The issue pertains to a situation where the content within the card overflows, causing unintended visual artifacts.

### Please Make the pull Request to "**2023 Branch**"

![image](https://github.com/iiitv/Arcadia-Auction/assets/97253470/3f304cb8-845a-4341-8c14-2314d56a34ab)

**Comment by bryanoli** [comment]
Hey @Mehul-Kumar-27, I would like to work on this issue.

**Comment by Mehul-Kumar-27** [comment]
> Hey @Mehul-Kumar-27, I would like to work on this issue.

Go for it @bryanoli 👍.

**Comment by bryanoli** [comment]
Hello @Mehul-Kumar-27. I have been trying to use the app locally by creating a Firebase project for it. I was wondering how did you set it up?

**Comment by Harini-01** [comment]
Hey @Mehul-Kumar-27, I would like to work on this issue. I am participating in hacktoberfest-2024. This would be my first open source contribution.

**Comment by Mehul-Kumar-27** [comment]
Hey @Harini-01 , thanks for reaching this issue is still open you can definitely pick this up, but I am not sure whether this year IIITV community have applied for hacktoberfest 2024 :)

**Comment by Mehul-Kumar-27** [comment]
@Harini-01 , I just saw the rules for Hacktoberfest, and as far as I can see, any issue with the Hacktoberfest tag automatically becomes a part of it. So, I guess this issue is valid for Hacktoberfest

**Comment by Harini-01** [comment]
@Mehul-Kumar-27 Can you please assign this issue to me?

**Comment by aspiringgarv** [comment]
@Harini-01  Assigned your the issue

**Comment by JayAgola** [comment]
@aspiringgarv  Can I work on this issue?

**Comment by Harini-01** [comment]
![image](https://github.com/user-attachments/assets/7b206af6-4485-41f4-b289-564eaddf680a)
I am unable to reproduce the bug. i am getting this error when I try to run the app. Could you please help?

**Comment by aspiringgarv** [comment]
@JayAgola assigned
