### ISSUE TITLE
deprecated FlatButton usage in the project

### ISSUE THREAD

**Issue by JayAgola** [iiitv/Arcadia-Auction#34]
The project contains instances of the deprecated FlatButton widget, which needs to be updated to align with current Flutter practices. This issue aims to address the usage of outdated widgets to ensure future compatibility and maintainability of the codebase.

![Screenshot 2024-09-30 145144](https://github.com/user-attachments/assets/5c665b8b-f18d-4e62-816e-a8e1928b1ecf)

**Comment by JayAgola** [comment]
@iiitv/flutter-maintainers Can I work on this if this feels like a valid issue?

**Comment by Mehul-Kumar-27** [comment]
> @iiitv/flutter-maintainers Can I work on this if this feels like a valid issue?

@aspiringgarv

**Comment by Mehul-Kumar-27** [comment]
Part of #36
