### ISSUE TITLE
Run the application 

### ISSUE THREAD

**Issue by Mehul-Kumar-27** [iiitv/Arcadia-Auction#36]
- The project has been inactive for many months i highly doubt that this would run in a single go, so please try to build the application in dev mode on your local and fix the dependencies wherever required. 
- Try to build the project with flutter version 3.22 + (as of 3 oct 2024 🙂)

**Comment by JayAgola** [comment]
Hello @Mehul-Kumar-27 , I would like to work on this issue.

**Comment by aspiringgarv** [comment]
@JayAgola Assigned(++)

**Comment by Amitkumarkoli** [comment]
hey! this is this still open??
I am also want to work on this.

**Comment by aspiringgarv** [comment]
@JayAgola  any update on the issue

**Comment by JayAgola** [comment]
@aspiringgarv Yes i am working on that and i will try to update this code flutter latest version 3.24

**Comment by Mehul-Kumar-27** [comment]
Solved by #38
