### ISSUE TITLE
Pixel Overflow Issue in "Announcements Card"

### ISSUE THREAD

**Issue by JayAgola** [iiitv/Arcadia-Auction#39]
**Description**:

We are experiencing a pixel overflow issue in the "Announcements card" component. This results in elements extending beyond their intended boundaries, disrupting the overall layout.

![pixel overflow](https://github.com/user-attachments/assets/9dbbbe06-c0c9-46cc-9417-3cc31b1e918a)

**Comment by JayAgola** [comment]
@aspiringgarv  Can I work on this if this feels like a valid issue?

**Comment by aspiringgarv** [comment]
@JayAgola  assigned
